CELL_SIZE = 100
SIZE_OF_SQUARE = CELL_SIZE
MOVE_DURATION_MS = 1000
JUMP_DURATION_MS = 1000
DEFAULT_WAIT_MS = 1

COMMAND_CLICK = 'click'
COMMAND_WAIT = 'wait'
COMMAND_JUMP = 'jump'
COMMAND_PRINT_BOARD = 'print board'

