from view.draw import (
    ACCENT,
    BG_COLOR,
    CARD_COLOR,
    DARK,
    ERROR_COLOR,
    FONT,
    INPUT_BG,
    INPUT_BORDER,
    INPUT_BORDER_FOCUS,
    PANEL_COLOR,
    SUCCESS_COLOR,
    TABLE_ROW_ALT,
    TABLE_HOVER,
    TEXT_MUTED,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    WHITE,
    draw_rounded_rect,
    put_text,
    text_size,
)
from view.renderer import OpenCVRenderer
